# Generated by Django 4.1.2 on 2022-10-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='Song',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='datereleased',
            new_name='date_released',
        ),
        migrations.AlterField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
