# Generated by Django 4.1.2 on 2022-11-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_song_lyric_song_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_id',
        ),
    ]
