# Generated by Django 4.1.2 on 2022-11-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_remove_song_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
            preserve_default=False,
        ),
    ]
